# Generated by Django 5.0.3 on 2024-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_education_country_alter_fellowship_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='birthstateprovince',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Birth State/Province'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='mailingstateprovince',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Mailing State/Province'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='stateprovince',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=15, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-SD', 'South Dakota'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-UM', 'United States Minor Outlying Islands'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-OK', 'Oklahoma'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-TX', 'Texas'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-NH', 'New Hampshire'), ('US-PR', 'Puerto Rico'), ('US-LA', 'Louisiana'), ('US-WI', 'Wisconsin'), ('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-MA', 'Massachusetts'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MD', 'Maryland'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-RI', 'Rhode Island'), ('US-ME', 'Maine'), ('US-TN', 'Tennessee'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-SC', 'South Carolina'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-MO', 'Missouri')])], max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterModelTable(
            name='boardcertifications',
            table='BoardCertifications',
        ),
        migrations.AlterModelTable(
            name='dearegistration',
            table='DEARegistration',
        ),
        migrations.AlterModelTable(
            name='education',
            table='Education',
        ),
        migrations.AlterModelTable(
            name='fellowship',
            table='Fellowship',
        ),
        migrations.AlterModelTable(
            name='fifthpathway',
            table='FifthPathway',
        ),
        migrations.AlterModelTable(
            name='gschool',
            table='OtherGraduateSchool',
        ),
        migrations.AlterModelTable(
            name='informations',
            table='Informations',
        ),
        migrations.AlterModelTable(
            name='licences',
            table='Licences',
        ),
        migrations.AlterModelTable(
            name='licencesnotherexams',
            table='LicencesOtherExams',
        ),
        migrations.AlterModelTable(
            name='lifesupport',
            table='LifeSupport',
        ),
        migrations.AlterModelTable(
            name='medicaleducation',
            table='Medical Education',
        ),
        migrations.AlterModelTable(
            name='medicaltraining',
            table='MedicalTraining',
        ),
        migrations.AlterModelTable(
            name='preceptorship',
            table='Preceptorship',
        ),
        migrations.AlterModelTable(
            name='residency',
            table='Residency',
        ),
    ]
