# Generated by Django 5.0.3 on 2024-04-24 21:07

import app1.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_education_country_alter_fellowship_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, db_column='Administrative Area L1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.CharField(blank=True, db_column='Locality', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, db_column='Postal Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='route',
            field=models.CharField(blank=True, db_column='Route', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.CharField(blank=True, db_column='Street Number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='boardtype',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Board Type', max_length=20, null=True, verbose_name='Board Type'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='cdate',
            field=models.DateField(blank=True, db_column='Certified Date', default=django.utils.timezone.now, verbose_name='Certified Date'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='certified',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Certified', max_length=20, null=True, verbose_name='Certified'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='datesch',
            field=models.DateField(blank=True, db_column='Date Scheduled', default=django.utils.timezone.now, verbose_name='Date Scheduled'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='degree',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='expdate',
            field=models.DateField(blank=True, db_column='Expiration Date', default=django.utils.timezone.now, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='ifnot',
            field=models.TextField(blank=True, db_column='If not', null=True, verbose_name='If Not certified, how many times have you taken a specialty board and failed to pass?'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='ifnotcert',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='If not cert', max_length=20, null=True, verbose_name='If not certified, have you been accepted to take a specialty examination?'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='lftmcert',
            field=models.CharField(choices=[('', [('yes', 'Yes'), ('no', 'No')])], db_column='Lifetime Cert', max_length=20, verbose_name='Lifetime Certification?'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='ofspeciality',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Of Speciality', max_length=20, null=True, verbose_name='Of (Speciality)'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='rcdate',
            field=models.DateField(blank=True, db_column='Recertified Date', default=django.utils.timezone.now, verbose_name='Recertified Date'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='recertified',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Recertified', max_length=20, null=True, verbose_name='Recertified'),
        ),
        migrations.AlterField(
            model_name='boardcertifications',
            name='withcertification',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='With Certification', max_length=20, null=True, verbose_name='With Certification In (if applicable)'),
        ),
        migrations.AlterField(
            model_name='dearegistration',
            name='dissued',
            field=models.DateField(blank=True, db_column='Dissued', default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='dearegistration',
            name='expdate',
            field=models.DateField(blank=True, db_column='Expdate', default=django.utils.timezone.now, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='dearegistration',
            name='ifu',
            field=models.TextField(blank=True, db_column='IFU', null=True, verbose_name='If you do not currently possess a DEA Registration, please explain here:'),
        ),
        migrations.AlterField(
            model_name='dearegistration',
            name='rnumber',
            field=models.CharField(db_column='Reg Number', max_length=20, null=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='dearegistration',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='education',
            name='address',
            field=models.CharField(db_column='Address', max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.CharField(db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='education',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(blank=True, db_column='Date of G', default=django.utils.timezone.now, verbose_name='Date of Graduation'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degreeaw',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree Awarded', max_length=20, null=True, verbose_name='Degree Awarded'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end',
            field=models.DateField(blank=True, db_column='End', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduated',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Graduated', max_length=20, null=True, verbose_name='Graduated'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(db_column='Institution', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start',
            field=models.DateField(blank=True, db_column='Start', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='education',
            name='zip',
            field=models.CharField(db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='address',
            field=models.CharField(db_column='Address', max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='city',
            field=models.CharField(db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='end',
            field=models.DateField(blank=True, db_column='End', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='gsurgery',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='ifnot',
            field=models.TextField(blank=True, db_column='If not', null=True, verbose_name='If Not Completed, please explain'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='institution',
            field=models.CharField(db_column='Institution', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='pchair',
            field=models.CharField(db_column='Program Chair', max_length=20, null=True, verbose_name='Program Chair'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='programc',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Pprogram C', max_length=20, null=True, verbose_name='Program Completed'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='speciality',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Speciality', max_length=20, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='start',
            field=models.DateField(blank=True, db_column='Start', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='zip',
            field=models.CharField(db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='fifthpathway',
            name='file',
            field=models.FileField(db_column='File', upload_to=app1.models.user_directory_path_fifthpathway),
        ),
        migrations.AlterField(
            model_name='fifthpathway',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='address',
            field=models.CharField(db_column='Address', max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='city',
            field=models.CharField(db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='date',
            field=models.DateField(blank=True, db_column='Date of G', default=django.utils.timezone.now, verbose_name='Date of Graduation'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='degree',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='degreeaw',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree Awarded', max_length=20, null=True, verbose_name='Degree Awarded'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='end',
            field=models.DateField(blank=True, db_column='End', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='graduated',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Graduated', max_length=20, null=True, verbose_name='Graduated'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='institution',
            field=models.CharField(db_column='Institution', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='start',
            field=models.DateField(blank=True, db_column='Start', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='gschool',
            name='zip',
            field=models.CharField(db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='abletoworkintheusa',
            field=models.BooleanField(blank=True, db_column='Able to work USA', default=False, verbose_name='Are you able to work legally in the USA'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='birthcity',
            field=models.CharField(blank=True, db_column='Birth City', max_length=100, null=True, verbose_name='Birth City'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='birthcountry',
            field=models.CharField(blank=True, db_column='Birth Country', max_length=100, null=True, verbose_name='Birth Country'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='birthstateprovince',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Birth State/Province', max_length=100, null=True, verbose_name='Birth State/Province'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='emergencycontactemail',
            field=models.CharField(blank=True, db_column='Emergency Email', max_length=100, null=True, verbose_name='Emergency Contact Email'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='emergencycontactname',
            field=models.CharField(blank=True, db_column='Emergency Name', max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='emergencycontactnumber',
            field=models.CharField(blank=True, db_column='Emergency Number', max_length=100, null=True, verbose_name='Emergency Contact Number'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='generalsurgery',
            field=models.CharField(blank=True, db_column='General Surgery', max_length=100, null=True, verbose_name='General Surgery'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='languagesspokenotherthanenglish',
            field=models.CharField(blank=True, db_column='Other Languages', max_length=100, null=True, verbose_name='Languages  Spoken other than English'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='mailaddress',
            field=models.CharField(blank=True, db_column='Mailing Address', max_length=100, null=True, verbose_name='Mailing Address'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='mailcity',
            field=models.CharField(blank=True, db_column='Mailing City', max_length=100, null=True, verbose_name='Mailing City'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='mailingcountry',
            field=models.CharField(blank=True, db_column='Mailing Country', max_length=100, null=True, verbose_name='Mailing Country'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='mailingstateprovince',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Mailing State/Province', max_length=100, null=True, verbose_name='Mailing State/Province'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='mailingzipcode',
            field=models.CharField(blank=True, db_column='Mailing Zip Code', max_length=5, null=True, verbose_name='Mailing Zip Code'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='npinumber',
            field=models.CharField(blank=True, db_column='NPI Number', max_length=100, null=True, verbose_name='NPI NUMBER'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='otherphone',
            field=models.CharField(blank=True, db_column='Other Phone', max_length=10, null=True, verbose_name='Other Phone'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='preferredphonetype',
            field=models.CharField(blank=True, choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Preferred Phone Type', max_length=20, verbose_name='Preferred Phone Type'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='preffix',
            field=models.CharField(blank=True, choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Prefix', max_length=20, null=True, verbose_name='Preffix'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='primaryspeciality',
            field=models.CharField(blank=True, db_column='Primary Speciality', max_length=100, null=True, verbose_name='Primary Speciality'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='relationshiptoapplicant',
            field=models.CharField(blank=True, db_column='Relationship To Applicant', max_length=100, null=True, verbose_name='Relationship To Applicant'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='secondaryspeciality',
            field=models.CharField(blank=True, db_column='Secondary Speciality', max_length=100, null=True, verbose_name='Secondary Speciality'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='socialsecuritynumber',
            field=models.CharField(blank=True, db_column='Social Security Number', max_length=10, verbose_name='Social Security Number'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='stateprovince',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='State/Province', max_length=15, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Sufix', max_length=20, null=True, verbose_name='Suffix'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='workauthorizationa',
            field=models.CharField(blank=True, choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Work Auth', max_length=100, null=True, verbose_name='Work Authorization'),
        ),
        migrations.AlterField(
            model_name='informations',
            name='zipcode',
            field=models.CharField(blank=True, db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='licences',
            name='dissued',
            field=models.DateField(blank=True, db_column='Date Issued', default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='licences',
            name='expdate',
            field=models.DateField(blank=True, db_column='Expiration Date', default=django.utils.timezone.now, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='licences',
            name='lnumber',
            field=models.CharField(db_column='Licence Number', max_length=20, null=True, verbose_name='Licence Number'),
        ),
        migrations.AlterField(
            model_name='licences',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='licencesnotherexams',
            name='ecfmgandfmgems',
            field=models.DateField(blank=True, db_column='ecfmgandfmgems', default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='licencesnotherexams',
            name='ecfmgcnumber',
            field=models.CharField(db_column='ecfmgcnumber', max_length=20, null=True, verbose_name='ECFMG Certificate Number'),
        ),
        migrations.AlterField(
            model_name='licencesnotherexams',
            name='lexaminations',
            field=models.FileField(blank=True, db_column='lexaminations', null=True, upload_to=app1.models.user_directory_path_licensenother, verbose_name='Add License Exam'),
        ),
        migrations.AlterField(
            model_name='lifesupport',
            name='file',
            field=models.FileField(db_column='File', upload_to=app1.models.user_directory_path_lifesupport),
        ),
        migrations.AlterField(
            model_name='lifesupport',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='address',
            field=models.CharField(db_column='Address', max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='city',
            field=models.CharField(db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='date',
            field=models.DateField(blank=True, db_column='Date of G', default=django.utils.timezone.now, verbose_name='Date of Graduation'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='degree',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='degreeaw',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree Awarded', max_length=20, null=True, verbose_name='Degree Awarded'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='end',
            field=models.DateField(blank=True, db_column='End', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='explain',
            field=models.TextField(blank=True, db_column='Explain', null=True, verbose_name='For US/Canadian Medical School: If Medical School is greater or less than 4 years, please explain:'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='graduated',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Graduated', max_length=20, null=True, verbose_name='Graduated'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='institution',
            field=models.CharField(db_column='Institution', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='start',
            field=models.DateField(blank=True, db_column='Start', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='zip',
            field=models.CharField(db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='address',
            field=models.CharField(db_column='Address', max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='city',
            field=models.CharField(db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='degree',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='degreeaw',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree Awarded', max_length=20, null=True, verbose_name='Degree Awarded'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='end',
            field=models.DateField(blank=True, db_column='End', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='ifnot',
            field=models.TextField(blank=True, db_column='If Not', null=True, verbose_name='If Not Completed, please explain'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='institution',
            field=models.CharField(db_column='Institution', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='programc',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Program C', max_length=20, null=True, verbose_name='Program Completed'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='rotating',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Rotating', max_length=20, null=True, verbose_name='Rotating'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='start',
            field=models.DateField(blank=True, db_column='Start', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='zip',
            field=models.CharField(db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='preceptorship',
            name='file',
            field=models.FileField(db_column='File', upload_to=app1.models.user_directory_path_preceptorship),
        ),
        migrations.AlterField(
            model_name='preceptorship',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Uploaded at'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='address',
            field=models.CharField(db_column='Address', max_length=20, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='city',
            field=models.CharField(db_column='City', max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-CO', 'Colorado'), ('US-NJ', 'New Jersey'), ('US-RI', 'Rhode Island'), ('US-WV', 'West Virginia'), ('US-CT', 'Connecticut'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-SC', 'South Carolina'), ('US-WY', 'Wyoming'), ('US-DC', 'District of Columbia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-PR', 'Puerto Rico'), ('US-DE', 'Delaware'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-WI', 'Wisconsin'), ('US-TN', 'Tennessee'), ('US-FL', 'Florida'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-SD', 'South Dakota'), ('US-TX', 'Texas'), ('US-GA', 'Georgia'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GU', 'Guam'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-HI', 'Hawaii'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-IA', 'Iowa'), ('US-NH', 'New Hampshire'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-UM', 'United States Minor Outlying Islands'), ('US-ID', 'Idaho'), ('US-UT', 'Utah'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-IL', 'Illinois'), ('US-VA', 'Virginia'), ('US-AR', 'Arkansas'), ('US-NC', 'North Carolina'), ('US-IN', 'Indiana'), ('US-VI', 'Virgin Islands, U.S.'), ('US-AS', 'American Samoa'), ('US-ND', 'North Dakota'), ('US-KS', 'Kansas'), ('US-VT', 'Vermont'), ('US-AZ', 'Arizona'), ('US-NE', 'Nebraska'), ('US-KY', 'Kentucky'), ('US-WA', 'Washington'), ('US-CA', 'California'), ('US-LA', 'Louisiana')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='end',
            field=models.DateField(blank=True, db_column='End', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='residency',
            name='gsurgery',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Degree', max_length=20, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='ifnot',
            field=models.TextField(blank=True, db_column='If Not', null=True, verbose_name='If Not Completed, please explain'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='institution',
            field=models.CharField(db_column='Institution', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='residency',
            name='pchair',
            field=models.CharField(db_column='Program Chair', max_length=20, null=True, verbose_name='Program Chair'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='programc',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Program C', max_length=20, null=True, verbose_name='Program Completed'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='speciality',
            field=models.CharField(choices=[('', [('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3')])], db_column='Speciality', max_length=20, null=True, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='start',
            field=models.DateField(blank=True, db_column='Start', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='residency',
            name='state',
            field=models.CharField(db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='zip',
            field=models.CharField(db_column='ZCode', max_length=5, null=True, verbose_name='Zip Code'),
        ),
    ]
