# Generated by Django 5.0.3 on 2024-05-15 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_education_state_alter_fellowship_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='state',
            field=models.CharField(choices=[('', [('US-ND', 'North Dakota'), ('US-IN', 'Indiana'), ('US-AS', 'American Samoa'), ('US-TN', 'Tennessee'), ('US-NE', 'Nebraska'), ('US-KS', 'Kansas'), ('US-AZ', 'Arizona'), ('US-TX', 'Texas'), ('US-NH', 'New Hampshire'), ('US-KY', 'Kentucky'), ('US-CA', 'California'), ('US-UM', 'United States Minor Outlying Islands'), ('US-NJ', 'New Jersey'), ('US-LA', 'Louisiana'), ('US-CO', 'Colorado'), ('US-UT', 'Utah'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-CT', 'Connecticut'), ('US-VA', 'Virginia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-DC', 'District of Columbia'), ('US-VI', 'Virgin Islands, U.S.'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-DE', 'Delaware'), ('US-VT', 'Vermont'), ('US-NC', 'North Carolina'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-WA', 'Washington'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-WI', 'Wisconsin'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-GU', 'Guam'), ('US-WV', 'West Virginia'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-HI', 'Hawaii'), ('US-WY', 'Wyoming'), ('US-PR', 'Puerto Rico'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-IA', 'Iowa'), ('US-RI', 'Rhode Island'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-ID', 'Idaho'), ('US-SC', 'South Carolina'), ('US-AR', 'Arkansas'), ('US-IL', 'Illinois'), ('US-SD', 'South Dakota')])], db_column='State', max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='fellowship',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-ND', 'North Dakota'), ('US-IN', 'Indiana'), ('US-AS', 'American Samoa'), ('US-TN', 'Tennessee'), ('US-NE', 'Nebraska'), ('US-KS', 'Kansas'), ('US-AZ', 'Arizona'), ('US-TX', 'Texas'), ('US-NH', 'New Hampshire'), ('US-KY', 'Kentucky'), ('US-CA', 'California'), ('US-UM', 'United States Minor Outlying Islands'), ('US-NJ', 'New Jersey'), ('US-LA', 'Louisiana'), ('US-CO', 'Colorado'), ('US-UT', 'Utah'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-CT', 'Connecticut'), ('US-VA', 'Virginia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-DC', 'District of Columbia'), ('US-VI', 'Virgin Islands, U.S.'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-DE', 'Delaware'), ('US-VT', 'Vermont'), ('US-NC', 'North Carolina'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-WA', 'Washington'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-WI', 'Wisconsin'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-GU', 'Guam'), ('US-WV', 'West Virginia'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-HI', 'Hawaii'), ('US-WY', 'Wyoming'), ('US-PR', 'Puerto Rico'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-IA', 'Iowa'), ('US-RI', 'Rhode Island'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-ID', 'Idaho'), ('US-SC', 'South Carolina'), ('US-AR', 'Arkansas'), ('US-IL', 'Illinois'), ('US-SD', 'South Dakota')])], db_column='', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='medicaleducation',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-ND', 'North Dakota'), ('US-IN', 'Indiana'), ('US-AS', 'American Samoa'), ('US-TN', 'Tennessee'), ('US-NE', 'Nebraska'), ('US-KS', 'Kansas'), ('US-AZ', 'Arizona'), ('US-TX', 'Texas'), ('US-NH', 'New Hampshire'), ('US-KY', 'Kentucky'), ('US-CA', 'California'), ('US-UM', 'United States Minor Outlying Islands'), ('US-NJ', 'New Jersey'), ('US-LA', 'Louisiana'), ('US-CO', 'Colorado'), ('US-UT', 'Utah'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-CT', 'Connecticut'), ('US-VA', 'Virginia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-DC', 'District of Columbia'), ('US-VI', 'Virgin Islands, U.S.'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-DE', 'Delaware'), ('US-VT', 'Vermont'), ('US-NC', 'North Carolina'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-WA', 'Washington'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-WI', 'Wisconsin'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-GU', 'Guam'), ('US-WV', 'West Virginia'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-HI', 'Hawaii'), ('US-WY', 'Wyoming'), ('US-PR', 'Puerto Rico'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-IA', 'Iowa'), ('US-RI', 'Rhode Island'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-ID', 'Idaho'), ('US-SC', 'South Carolina'), ('US-AR', 'Arkansas'), ('US-IL', 'Illinois'), ('US-SD', 'South Dakota')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='medicaltraining',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-ND', 'North Dakota'), ('US-IN', 'Indiana'), ('US-AS', 'American Samoa'), ('US-TN', 'Tennessee'), ('US-NE', 'Nebraska'), ('US-KS', 'Kansas'), ('US-AZ', 'Arizona'), ('US-TX', 'Texas'), ('US-NH', 'New Hampshire'), ('US-KY', 'Kentucky'), ('US-CA', 'California'), ('US-UM', 'United States Minor Outlying Islands'), ('US-NJ', 'New Jersey'), ('US-LA', 'Louisiana'), ('US-CO', 'Colorado'), ('US-UT', 'Utah'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-CT', 'Connecticut'), ('US-VA', 'Virginia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-DC', 'District of Columbia'), ('US-VI', 'Virgin Islands, U.S.'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-DE', 'Delaware'), ('US-VT', 'Vermont'), ('US-NC', 'North Carolina'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-WA', 'Washington'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-WI', 'Wisconsin'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-GU', 'Guam'), ('US-WV', 'West Virginia'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-HI', 'Hawaii'), ('US-WY', 'Wyoming'), ('US-PR', 'Puerto Rico'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-IA', 'Iowa'), ('US-RI', 'Rhode Island'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-ID', 'Idaho'), ('US-SC', 'South Carolina'), ('US-AR', 'Arkansas'), ('US-IL', 'Illinois'), ('US-SD', 'South Dakota')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='residency',
            name='country',
            field=models.CharField(blank=True, choices=[('', [('US-ND', 'North Dakota'), ('US-IN', 'Indiana'), ('US-AS', 'American Samoa'), ('US-TN', 'Tennessee'), ('US-NE', 'Nebraska'), ('US-KS', 'Kansas'), ('US-AZ', 'Arizona'), ('US-TX', 'Texas'), ('US-NH', 'New Hampshire'), ('US-KY', 'Kentucky'), ('US-CA', 'California'), ('US-UM', 'United States Minor Outlying Islands'), ('US-NJ', 'New Jersey'), ('US-LA', 'Louisiana'), ('US-CO', 'Colorado'), ('US-UT', 'Utah'), ('US-NM', 'New Mexico'), ('US-MA', 'Massachusetts'), ('US-CT', 'Connecticut'), ('US-VA', 'Virginia'), ('US-NV', 'Nevada'), ('US-MD', 'Maryland'), ('US-DC', 'District of Columbia'), ('US-VI', 'Virgin Islands, U.S.'), ('US-NY', 'New York'), ('US-ME', 'Maine'), ('US-DE', 'Delaware'), ('US-VT', 'Vermont'), ('US-NC', 'North Carolina'), ('US-OH', 'Ohio'), ('US-MI', 'Michigan'), ('US-FL', 'Florida'), ('US-WA', 'Washington'), ('US-OK', 'Oklahoma'), ('US-MN', 'Minnesota'), ('US-GA', 'Georgia'), ('US-WI', 'Wisconsin'), ('US-OR', 'Oregon'), ('US-MO', 'Missouri'), ('US-GU', 'Guam'), ('US-WV', 'West Virginia'), ('US-PA', 'Pennsylvania'), ('US-MP', 'Northern Mariana Islands'), ('US-HI', 'Hawaii'), ('US-WY', 'Wyoming'), ('US-PR', 'Puerto Rico'), ('US-AK', 'Alaska'), ('US-MS', 'Mississippi'), ('US-IA', 'Iowa'), ('US-RI', 'Rhode Island'), ('US-AL', 'Alabama'), ('US-MT', 'Montana'), ('US-ID', 'Idaho'), ('US-SC', 'South Carolina'), ('US-AR', 'Arkansas'), ('US-IL', 'Illinois'), ('US-SD', 'South Dakota')])], db_column='Country', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verify', 'Verified'), ('unverify', 'Unverified')], default='pending', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
